[tool.mypy]
scripts_are_modules = true
show_traceback = true

[[tool.mypy.overrides]]
module = [
    "openpyxl.*",
    "stanfordcorenlp.*",
    "psutil.*",
    "bs4.*",
]
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "server.settings"

[tool.isort]
profile = "black"